creation of the Create your art page and some changes to the menu.
algopainter/algopainter-app pull request #2
Opened 2021-06-11 18:35 UTC by FranBernardo

creation of the Create your art page and some changes to the menu.

2021-06-15 13:15 UTC, jpauloamartins requested changes

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +        v-model="textType" required class="full-width typeText"/>
Utilizar component de input do Quasar.
Corrigir indentação.

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +        </q-img>
```suggestion
        <q-img
          src="../../../assets/images/hashly-gwei.svg"
          style="height: 429px; width: 230px; border:none;"
        />
```

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +          style="height: 429px; width: 230px; border:none;">
Não utilizar estilos inline.

2021-06-15 13:15 UTC, jpauloamartins commented on src/components/DashboardHeader.vue
> +
```suggestion

.menu{
  background: white;
  border: 6px solid white;
}
```

2021-06-15 13:15 UTC, jpauloamartins commented on src/components/SideBar.vue
> +        to: '/newpainting',
```suggestion
        to: '/new-painting',
```

2021-06-15 13:15 UTC, jpauloamartins commented on src/i18n/en-US/dashboard.ts
> +
```suggestion
    title: 'New Painting',
    create: 'Create Your Art',
    typeAText: 'Type a text',
    paintOnWall: 'Hang the paint  on Wall?',
    coresAleatórias: 'Apply randon color inversion:',
    collorInversionProbability: 'Define the collor inversion probability',
    yourInspiration: 'Your Inspiration',
    trace: '/',
    genarate: 'Genarate Painting',
  },
```

2021-06-15 13:15 UTC, jpauloamartins commented on src/i18n/en-US/dashboard.ts
> +    CoresAleatórias: 'Apply randon color inversion:',
```suggestion
    randomColors: 'Apply randon color inversion:',
```

2021-06-15 13:15 UTC, jpauloamartins commented on src/i18n/en-US/dashboard.ts
> +    CollorInversionProbability: 'Define the collor inversion probability',
```suggestion
    colorInversionProbability: 'Define the collor inversion probability',
```

2021-06-15 13:15 UTC, jpauloamartins commented on src/layouts/MainLayout.vue
> +    <q-header reveal >
```suggestion
    <q-header class="q-py-lg bg-transparent">
```

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +            <q-radio  v-model="hang" val="No" label="No"></q-radio>
Colocar valor do label no arquivo de mensagens.

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +            <q-radio v-model="range" val="no" label="No"></q-radio>
Colocar valor do label no arquivo de mensagens.

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +                <q-radio  v-model="test" val="Random" label="Random"></q-radio>
Colocar valor do label no arquivo de mensagens.

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +                <q-radio  v-model="test" val="Calm" label="Calm"></q-radio>
Colocar valor do label no arquivo de mensagens.

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +                val="Colorfull blocks" label="Colorfull blocks"/>
```suggestion
                <q-radio
                   v-model="test"
                  val="Colorfull blocks"
                  label="Colorfull blocks"
                />
```
Colocar valor do label no arquivo de mensagens.

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +                <q-radio  v-model="test" val="Hot flows" label="Hot flows"/>
Colocar valor do label no arquivo de mensagens.

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +                val="Colorfull paths" label="Colorfull paths"/>
Corrigir indentação.
Colocar valor do label no arquivo de mensagens.

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +                <q-radio  v-model="test" val="Galaxy" label="Galaxy"></q-radio>
Colocar valor do label no arquivo de mensagens.

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +            <q-btn color="primary" class="q-px-xl" label="Genarate Painting"/>
Colocar label no arquivo de mensagens.

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +                <q-radio  v-model="test" val="5000 Days" label="5000 Days"/>
Colocar valor do label no arquivo de mensagens.

2021-06-15 13:15 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +  private hang: string = 'line'
```suggestion
  private textType: string = '';
  private limit: number = 64;
  private empty: number = 0;
  private test: string = 'line';
  private slider: number = 0;
  private range: string = '';
  private hang: string = 'line';
```

2021-06-15 13:15 UTC, jpauloamartins commented on src/router/routes.ts
> +        path: 'newpainting',
```suggestion
        path: 'new-painting',
```

2021-06-15 13:15 UTC, jpauloamartins commented on src/i18n/en-US/dashboard.ts
> +  newpainting: {
```suggestion
  newPainting: {
```

2021-06-15 18:58 UTC, jpauloamartins requested changes

2021-06-15 18:58 UTC, jpauloamartins commented on src/i18n/en-US/dashboard.ts
> +    CoresAleatórias: 'Apply randon color inversion:',
Para manter o padrão, a chave deve sempre ser escrita com camelCase, com a prineira letra minúscula.

2021-06-15 18:58 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +  private icon: boolean = false;
Os nomes das variáveis devem indicar o que essa variável guarda.

Os dados de um formulário devem ser salvos em um objeto.

Valores boolean devem seguir um padrão de nomenclatura: https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig

2021-06-15 18:58 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +  private empty: number = 0;
Qual a necessidade dessa variável?

2021-06-15 18:58 UTC, jpauloamartins commented on src/pages/dashboard/newpaint/NewPainting.vue
> +  }
É necessário criar essa `computed property`?

2021-06-15 19:01 UTC, jpauloamartins requested changes

2021-06-15 19:01 UTC, jpauloamartins commented on src/components/DashboardHeader.vue
> +  <q-toolbar class="menu">
```suggestion
  <q-toolbar class="q-pa-none">
```

2021-06-15 19:01 UTC, jpauloamartins commented on src/components/DashboardHeader.vue
>    display: flex;
```suggestion
.nav-bar {
  display: flex;

```

2021-06-15 23:27 UTC, FranBernardo commented on src/pages/dashboard/newpaint/NewPainting.vue
> +  private empty: number = 0;
Essa variável faz o a contagem de cada letra que o usuário digita para por o limite de 64 caracteres.

2021-06-15 23:28 UTC, FranBernardo commented on src/pages/dashboard/newpaint/NewPainting.vue
> +  }
ele faz a contagem de cada caractere que o usuário digita para colocar o limite de 64 caracteres .

2021-06-15 23:38 UTC, FranBernardo commented on src/components/DashboardHeader.vue
> +  <q-toolbar class="menu">
se tirar a classe menu ele fica com o background todo rosa. Adicionei a class q-pa-none e deixei a classe background menu com o background branco.

2021-06-18 06:03 UTC, jpauloamartins approved these changes

2021-06-18 06:03 UTC, merged