Feature/auctions info
algopainter/algopainter-app pull request #3
Opened 2021-06-18 13:26 UTC by BrunoArrais

code analysis

2021-06-18 18:32 UTC, BrunoArrais commented
resolve conflicts

2021-06-18 18:33 UTC, BrunoArrais commented
resolve conflicts

2021-06-19 00:09 UTC, gleissonassis requested changes

2021-06-19 00:09 UTC, gleissonassis commented on src/assets/icons/bidblock.svg
> +</svg>
Renomear o arquivo para bidback. O nome bid block está incorreto.

2021-06-19 00:09 UTC, gleissonassis commented on src/components/SideBar.vue
> +        to: '/auctionsinfo',
O padrão para nomes de url deve seguir algo como:
https://api.gov.au/standards/national_api_standards/naming-conventions.html

Em resumo se tiver mais de uma palavra deve-se separar por hifen.

Alterar para /auctions-info

2021-06-23 20:49 UTC, closed without merging